### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mukral** [CadQuery/cadquery#1213]
Hi, 
I'm running Ubuntu 22.04 LTS with python 3.10 (installed via apt) and cadquery installed with pip
pip list shows:
cadquery               2.2.0b2
cadquery-ocp           7.6.3a0

Just testing with:
```
import cadquery as cq
test1 = cq.Workplane().circle(2).extrude(2)
```
I got this error back:
Traceback (most recent call last):
  File "/var/www/html/cadqueryTest1.py", line 1, in <module>
    import cadquery as cq
  File "/usr/local/lib/python3.10/dist-packages/cadquery/__init__.py", line 10, in <module>
    from .occ_impl.geom import Plane, BoundBox, Vector, Matrix, Location
  File "/usr/local/lib/python3.10/dist-packages/cadquery/occ_impl/geom.py", line 5, in <module>
    from OCP.gp import (
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Does anybody has an idea how to fix?

Thank you very much
Markus

**Comment by mukral** [comment]
ah, ubuntu server version is installed not desktop-version.
For server no graphic is needed and the libraries are not installed by default.
So the solution is:
apt-get install libgl1-mesa-glx

Markus
