### ISSUE TITLE
_importDXF wire_set throw "IndexError: list index out of range"

### ISSUE THREAD

**Issue by tp1415926535** [CadQuery/cadquery#1274]
script:
``` python
import cadquery
result = cadquery.importers.importDXF("D:/Machine.dxf")
```
output:
``` console
Traceback (most recent call last):
  File "D:\python scripts\cadTrans.py", line 2, in <module>
    result = cadquery.importers.importDXF("D:/Machine.dxf")
  File "D:\Python3.9.13\lib\site-packages\cadquery\occ_impl\importers\__init__.py", line 86, in importDXF
    faces = _importDXF(filename, tol, exclude, include)
  File "D:\Python3.9.13\lib\site-packages\cadquery\occ_impl\importers\dxf.py", line 198, in _importDXF
    faces.append(Face.makeFromWires(wire_set[0], wire_set[1:]))
IndexError: list index out of range
```
the dxf file:
[Machine.zip](https://github.com/CadQuery/cadquery/files/10738421/Machine.zip)

**Comment by adam-urbanczyk** [comment]
CQ does not support `ezdxf.entities.acis.Solid3d`.
