### ISSUE TITLE
ImportError: cannot import name 'zoom' from 'ezdxf' (/opt/conda/lib/python3.12/site-packages/ezdxf/__init__.py)

### ISSUE THREAD

**Issue by pmbaumgartner** [CadQuery/cadquery#1704]
On a fresh install (on macOS, using docker) I get:

```
ImportError: cannot import name 'zoom' from 'ezdxf' (/opt/conda/lib/python3.12/site-packages/ezdxf/__init__.py)
```

full traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.12/site-packages/cadquery/__init__.py", line 22, in <module>
    from .occ_impl import exporters
  File "/opt/conda/lib/python3.12/site-packages/cadquery/occ_impl/exporters/__init__.py", line 18, in <module>
    from .dxf import exportDXF, DxfDocument
  File "/opt/conda/lib/python3.12/site-packages/cadquery/occ_impl/exporters/dxf.py", line 6, in <module>
    from ezdxf import units, zoom
ImportError: cannot import name 'zoom' from 'ezdxf' (/opt/conda/lib/python3.12/site-packages/ezdxf/__init__.py)
```

**Comment by kariem2k** [comment]
This is happening to me too on Windows (Clean Conda installation). I tried 2.4 and master both cause the same error.

**Comment by jmwright** [comment]
Can you run `conda list` in your environment and post it here?

**Comment by kariem2k** [comment]
Of course
[condalist.txt](https://github.com/user-attachments/files/18276275/condalist.txt)

Attached the file.

**Comment by jmwright** [comment]
The version of ezdxf that output is showing is not even close to the current release. The oldest version I can find in my Linux environments is 1.1.0. I don't see any reason why conda would be installing an earlier version (a Windows package is available).

https://anaconda.org/conda-forge/ezdxf

Can you try to force the installation of 1.3.0 in your conda environment?

**Comment by jmwright** [comment]
@pmbaumgartner @kariem2k Are either of you able to try the potential solution above?

**Comment by jmwright** [comment]
@adam-urbanczyk Should we pin the version of ezdxf in environment.yml to force conda to use a current version? 

https://github.com/CadQuery/cadquery/blob/master/environment.yml#L16

**Comment by jmwright** [comment]
@shimwell I have not seen evidence that pip is affected, have you? It seems like a conda solver issue. We could go ahead and add the pin to setup.py for completeness anyway.

**Comment by jmwright** [comment]
@shimwell No worries. Some conda and pip packages are also maintained separately, so the versions do not always match up (one can lag the other). So that adds another layer of consideration to this. However, I do see that PyPI has version 1.3.0 of ezdxf and above, so we could add the pin for >=1.3.0 to setup.py as well to be more  consistent between environments.

**Comment by jmwright** [comment]
I created #1746 to see if we can fix this.

**Comment by jmwright** [comment]
#1746 has been merged. I think it usually takes a few hours for the packages to be available on conda-forge. Can someone who can reproduce this issue test a conda master install of CadQuery when the new packages are available? I believe you can watch for the new master package on conda-forge. When it is available there, you can try the install.

https://anaconda.org/CadQuery/cadquery/files

**Comment by adam-urbanczyk** [comment]
Actually I need to update the recipe there.

**Comment by adam-urbanczyk** [comment]
Done
