### ISSUE TITLE
Plane._setPlaneDir Is Different Between CQ Versions

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery#282]
One of the cqparts tests is failing with CQ 2.0, complaining that `vector has zero norm`. The error seems to stem from [this method](https://github.com/CadQuery/cadquery/blob/master/cadquery/occ_impl/geom.py#L724). Here's where the error comes from in the cqparts codebase: https://github.com/jmwright/cqparts/blob/master/src/cqparts/utils/geometry.py#L38

It seems that `xDir` is found differently in CQ 2.0 than it is in CQ 1.0. Here's the same method from 1.0: https://github.com/dcowden/cadquery/blob/master/cadquery/freecad_impl/geom.py#L643

It almost has to be that `cross` is working differently in some cases, so I plan to start looking there.

@adam-urbanczyk Do you know why the code to find `xDir` varies between CQ 1.0 and CQ 2.0? Was it wrong in CQ 1.0?

**Comment by jmwright** [comment]
Here's the full cqparts error.
```
======================================================================
ERROR: test_random_failsafe (t_cqparts.test_coordsystem.CoordSystemTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jwright/anaconda3/envs/pywrap/lib/python3.6/site-packages/mock/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/home/jwright/Downloads/repos/cqparts/tests/t_cqparts/test_coordsystem.py", line 127, in test_random_failsafe
    cs = CoordSystem.random()
  File "/home/jwright/Downloads/repos/cqparts/src/cqparts/utils/geometry.py", line 199, in random
    normal=rand_vect(-1, 1),
  File "/home/jwright/Downloads/repos/cqparts/src/cqparts/utils/geometry.py", line 38, in __init__
    super(CoordSystem, self).__init__(origin, xDir, normal)
  File "/home/jwright/Downloads/repos/cadquery/cadquery/occ_impl/geom.py", line 472, in __init__
    self._setPlaneDir(xDir)
  File "/home/jwright/Downloads/repos/cadquery/cadquery/occ_impl/geom.py", line 718, in _setPlaneDir
    self.yDir = self.zDir.cross(self.xDir).normalized()
  File "/home/jwright/Downloads/repos/cadquery/cadquery/occ_impl/geom.py", line 122, in normalized
    return Vector(self.wrapped.Normalized())
OCP.Standard.Standard_ConstructionError: gp_Vec::Normalized() - vector has zero norm

----------------------------------------------------------------------
```

**Comment by jmwright** [comment]
Turns out that the test case was catching a RuntimeError for a specific error from FreeCAD. I switched that to using the equivalent OCP error and things seem fine now.
