### ISSUE TITLE
Assembly string selectors don't handle `and`

### ISSUE THREAD

**Issue by marcus7070** [CadQuery/cadquery#703]
## To Reproduce

```python
import cadquery as cq

assy = cq.Assembly(cq.Workplane().box(1, 1, 1), name="box")
assy._query("box @ vertices @ >X and >Y and >Z")
```

`assy._query("box @ vertices @ >X")` works as expected, the problem occurs with the `and`.

## Backtrace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/159r73f8jav6sm333b2j9jiqfxybq2r0-python3-3.8.7-env/lib/python3.8/site-packages/cadquery/assembly.py", line 290, in _query
    query = _grammar.parseString(q, True)
  File "/nix/store/159r73f8jav6sm333b2j9jiqfxybq2r0-python3-3.8.7-env/lib/python3.8/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/nix/store/159r73f8jav6sm333b2j9jiqfxybq2r0-python3-3.8.7-env/lib/python3.8/site-packages/pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected end of text, found 'a'  (at char 20), (line:1, col:21)
```

**Comment by adam-urbanczyk** [comment]
I think #704 fixes this, but still need to add some tests.
