### ISSUE TITLE
Export Assembly as TSJ

### ISSUE THREAD

**Issue by davidvpspace** [CadQuery/cadquery#736]
Hi there!

I have an assembly created by multiple parts in cadquery. I would like to export it as json mesh format to later apply some textures to the different parts. With cadquery, the assembly cannot be exported directly as .tjs since only .step and .xml is available.

I have tried a workaround to convert the assembly to a single piece by and then export it to .tjs

`
assy = assy.toCompound()
cq.exporters.export(assy, 'design1.json', tolerance=0.01, angularTolerance=0.1, exportType=exporters.ExportTypes.TJS)
`

However, I get the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7f7c910c646a> in <module>
----> 1 assy.toCompound()

AttributeError: 'Assembly' object has no attribute 'toCompound'
```

I have installed cadquery using the master branch so I should be able to use the attribute toCompound(). Do you have an idea of what could be the source of this? 

Also, is it in mind to add to cadquery a feature to specify material type to different parts of an assembly? 

Thank you !

**Comment by davidvpspace** [comment]
I have also try the solution from issue #629, but I get the following error:

`assy_solid = generate_solid_from_assembly(assy)`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-bf842f15567a> in <module>
----> 1 assy_solid = generate_solid_from_assembly(thruster)

<ipython-input-6-5f4c196566c5> in generate_solid_from_assembly(assy, fuse, name_filter_re)
      6             continue
      7 
----> 8         shape = val.obj.val()
      9 
     10         # get location

AttributeError: 'NoneType' object has no attribute 'val'
```

**Comment by davidvpspace** [comment]
I have also try the solution from issue #629, but I get the following error:

`assy_solid = generate_solid_from_assembly(assy)`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-bf842f15567a> in <module>
----> 1 assy_solid = generate_solid_from_assembly(assy)

<ipython-input-6-5f4c196566c5> in generate_solid_from_assembly(assy, fuse, name_filter_re)
      6             continue
      7 
----> 8         shape = val.obj.val()
      9 
     10         # get location

AttributeError: 'NoneType' object has no attribute 'val'
```

**Comment by fedorkotov** [comment]
Please provide a minimum (non)working example including the code that creates some assembly so that we can reproduce the problem.

**Comment by Jojain** [comment]
When did you installed cadquery ? The toCompound method has been merged yesterday, you might want to update your installation first to see if it solves the problem.

**Comment by davidvpspace** [comment]
I installed it a couple weeks ago. I tried to update it this morning. Maybe I should try again, is it done by doing:?

`conda install -c cadquery -c conda-forge cadquery=master`

**Comment by davidvpspace** [comment]
> Please provide a minimum (non)working example including the code that creates some assembly so that we can reproduce the problem.

This is the complete working code, but that is unable to create a single solid part:

```
import cadquery as cq
import re
import time
from typing import Optional

class CADCreator():
    
    def __init__(self, var=None):
        self.pmuDictInit = {"height":100, "width":100, "thickness":25, "attach_height":12,"chamfer":11, "n_emitter":8 } if var is None else var
        self.pmuDictInit["fillet"] = 2
        self.emitterDictInit = {"em_width":22, "gr_width":20, "depth":5, "t_grid":0.5, "hole_number":11, "spacing_grid_side_factor":8, "spacing_grid_factor":2}
        self.connector = {"spacing":2.54, "pin":0.635, "pin_grid":(26,4),"thickness":10}
        self.logoDictInit = {"t_logo":0.01, "side_logo":self.emitterDictInit["gr_width"]/(3+0.1)}
        self.cwidth = (self.emitterDictInit["em_width"]+self.emitterDictInit["gr_width"])/2
        self.d_hole = self.cwidth/(2*self.emitterDictInit["spacing_grid_side_factor"]+self.emitterDictInit["hole_number"]+self.emitterDictInit["spacing_grid_factor"]*(self.emitterDictInit["hole_number"]-1))
        self.sw = (self.pmuDictInit["width"]-3*self.emitterDictInit["em_width"])/8
        self.sh = (self.pmuDictInit["height"]-3*self.emitterDictInit["em_width"])/8
        self.connector["width"] = self.connector["spacing"]*self.connector["pin_grid"][0]
        self.connector["height"] = self.connector["spacing"]*self.connector["pin_grid"][1]
        self.pcbAttachPoints = [(-37.505,42.865),(36.195,42.865),(-40.005,-42.865),(40.005,-42.865)]
        self.pc104 = [90.2,95.9,15]
        
        self.emit_points_all = {"1":(-2*self.emitterDictInit["em_width"]/2-self.sw,-2*self.emitterDictInit["em_width"]/2-self.sh),"2":(0,-2*self.emitterDictInit["em_width"]/2-self.sh),\
                            "3":(2*self.emitterDictInit["em_width"]/2+self.sw,-2*self.emitterDictInit["em_width"]/2-self.sh),"4":(-2*self.emitterDictInit["em_width"]/2-self.sw,0),\
                            "5":(2*self.emitterDictInit["em_width"]/2+self.sw,0),"6":(-2*self.emitterDictInit["em_width"]/2-self.sw,2*self.emitterDictInit["em_width"]/2+self.sh),\
                            "7":(0,2*self.emitterDictInit["em_width"]/2+self.sh),"8":(2*self.emitterDictInit["em_width"]/2+self.sw,2*self.emitterDictInit["em_width"]/2+self.sh)}
            
        self.logo_points_purple = [(0,self.emitterDictInit["gr_width"]-self.logoDictInit["side_logo"]*2),(self.emitterDictInit["gr_width"]-self.logoDictInit["side_logo"]*2,
                                    self.emitterDictInit["gr_width"]-self.logoDictInit["side_logo"]*2), (-self.emitterDictInit["gr_width"]+self.logoDictInit["side_logo"]*2,0),\
                                   (self.emitterDictInit["gr_width"]-self.logoDictInit["side_logo"]*2,0),(-self.emitterDictInit["gr_width"]+self.logoDictInit["side_logo"]*2,\
                                    -self.emitterDictInit["gr_width"]+self.logoDictInit["side_logo"]*2),(0,-self.emitterDictInit["gr_width"]+self.logoDictInit["side_logo"]*2),\
                                    (self.emitterDictInit["gr_width"]-self.logoDictInit["side_logo"]*2,-self.emitterDictInit["gr_width"]+self.logoDictInit["side_logo"]*2)]
            
        self.logo_point_green =[(-self.emitterDictInit["gr_width"]+self.logoDictInit["side_logo"]*2,self.emitterDictInit["gr_width"]-self.logoDictInit["side_logo"]*2)]

        self.grid_holes = []
        for i in range(0,self.emitterDictInit["hole_number"]):
            for j in range(0,self.emitterDictInit["hole_number"]):
                if j%2==0:
                    self.grid_holes.append((self.cwidth/2-(self.emitterDictInit["spacing_grid_side_factor"]+0.5)*self.d_hole-self.d_hole*(self.emitterDictInit["spacing_grid_factor"]+1)*i,\
                                        -self.cwidth/2+(self.emitterDictInit["spacing_grid_side_factor"]+0.5)*self.d_hole+self.d_hole*(self.emitterDictInit["spacing_grid_factor"]+1)*j))
        for i in range(0,self.emitterDictInit["hole_number"]+1):
            for j in range(0,self.emitterDictInit["hole_number"]):
                if j%2>0:
                    self.grid_holes.append((self.cwidth/2-(self.emitterDictInit["spacing_grid_side_factor"]-(self.emitterDictInit["spacing_grid_factor"]+1)/2+0.5)*self.d_hole-self.d_hole*(self.emitterDictInit["spacing_grid_factor"]+1)*i,\
                                        -self.cwidth/2+(self.emitterDictInit["spacing_grid_side_factor"]+0.5)*self.d_hole+self.d_hole*(self.emitterDictInit["spacing_grid_factor"]+1)*j))
        if self.pmuDictInit["n_emitter"]==8:
            self.emit_points = [self.emit_points_all["1"],self.emit_points_all["2"],self.emit_points_all["3"],self.emit_points_all["4"],self.emit_points_all["5"],\
                                self.emit_points_all["6"],self.emit_points_all["7"],self.emit_points_all["8"]]
        elif self.pmuDictInit["n_emitter"]==6:
            self.emit_points = [self.emit_points_all["1"],self.emit_points_all["2"],self.emit_points_all["3"],self.emit_points_all["6"],self.emit_points_all["7"],self.emit_points_all["8"]]
            
        elif self.pmuDictInit["n_emitter"]==4:
            self.emit_points = [self.emit_points_all["1"],self.emit_points_all["3"],self.emit_points_all["6"],self.emit_points_all["8"]]
        self.pinPoints = []
        for i in range(0,self.connector["pin_grid"][0]):
            for j in range(0,self.connector["pin_grid"][1]):
                self.pinPoints.append((-self.connector["width"]/2+self.connector["spacing"]/2+self.connector["spacing"]*i,\
                                    self.connector["height"]/2-self.connector["spacing"]/2-self.connector["spacing"]*j))
        self.thruster = cq.Assembly()
    
    def buildPMU(self):
        self.pmuRGB = cq.Color(0.7725,0.7686,0.7490)
        self.pmu = cq.Workplane("front").rect(self.pc104[0],self.pc104[1]).extrude(self.pmuDictInit["thickness"]-self.pmuDictInit["attach_height"])\
                .edges("|Z").fillet(self.pmuDictInit['fillet'])\
                .faces(">Z").workplane().rect(self.pmuDictInit["width"],self.pmuDictInit["height"]).extrude(self.pmuDictInit["attach_height"])\
                .edges("|Z").chamfer(self.pmuDictInit["chamfer"])\
                .faces(">Z").workplane().pushPoints(self.pcbAttachPoints).hole(3.2)\
                .faces(">Z").workplane().pushPoints(self.emit_points).rect(self.emitterDictInit["em_width"],self.emitterDictInit["em_width"]).cutBlind(-self.emitterDictInit["depth"])\
                .faces(">Z").workplane().pushPoints(self.logo_points_purple).rect(self.logoDictInit["side_logo"],self.logoDictInit["side_logo"]).cutBlind(-self.logoDictInit["t_logo"])\
                .faces(">Z").workplane().pushPoints(self.logo_point_green).rect(self.logoDictInit["side_logo"],self.logoDictInit["side_logo"]).cutBlind(-self.logoDictInit["t_logo"])
    
    def buildEmitters(self):
        self.emitterRGB = cq.Color(0.4117,0.4039,0.3725)
        self.emitter = cq.Workplane("front").rect(self.emitterDictInit["em_width"],self.emitterDictInit["em_width"]).extrude(self.emitterDictInit["depth"])\
                .faces(">Z").workplane().rect(self.emitterDictInit["gr_width"],self.emitterDictInit["gr_width"]).cutBlind(-self.emitterDictInit["depth"]/2)\
                .faces(">Z").workplane().rect(self.cwidth,self.cwidth).cutBlind(-self.emitterDictInit["t_grid"])
        self.gridRGB = cq.Color(0.3254,0.3372,0.3294)
        self.grid = cq.Workplane("front").rect(self.emitterDictInit["gr_width"],self.emitterDictInit["gr_width"]).extrude(self.emitterDictInit["t_grid"])\
                .faces(">Z").workplane().pushPoints(self.grid_holes).hole(self.d_hole)
                
    def buildLogo(self):
        self.purpleRGB = cq.Color(0.4117,0.3490,0.8823)
        self.greenRGB = cq.Color(0.2823,0.9176,0.8313)
        self.logo_purple = cq.Workplane("front").pushPoints(self.logo_points_purple).rect(self.logoDictInit["side_logo"],self.logoDictInit["side_logo"]).extrude(self.logoDictInit["t_logo"])
        self.logo_green = cq.Workplane("front").pushPoints(self.logo_point_green).rect(self.logoDictInit["side_logo"],self.logoDictInit["side_logo"]).extrude(self.logoDictInit["t_logo"])
        
    def buildEbox(self):
        self.eboxRGB = cq.Color(0,0.549,0.29)
        self.busRGB = cq.Color(0,0,0)
        self.ebox = cq.Workplane("front").rect(self.pc104[0],self.pc104[1]).extrude(self.pc104[2])\
                .faces(">Z").workplane().pushPoints(self.pcbAttachPoints).hole(3.2)
        self.buskit = cq.Workplane("front").rect(self.connector["width"],self.connector["height"]).extrude(self.connector["thickness"])\
                .faces(">Z").workplane().pushPoints(self.pinPoints).rect(self.connector["pin"],self.connector["pin"]).cutBlind(-self.connector["thickness"])
    
    def buildAT(self):
        self.athena = cq.importers.importDXF("athena_letter_v3.dxf", tol =1e-06).wires().toPending().extrude(0.001).rotate((0,0,0),(1,0,0),90)
        self.athenaRGB = cq.Color(0,0,0,0.5)
        if self.pmuDictInit["thickness"]<35:
            self.factor_scale = (self.pmuDictInit["thickness"]-self.logoDictInit["t_logo"])*0.35
        else:
            self.factor_scale = self.pmuDictInit["width"]/6.211*0.8
        self.athena = self.scale(self.athena,self.factor_scale)
        
    def scale(self,workplane: cq.Workplane, x: float, y: Optional[float] = None, z: Optional[float] = None) -> cq.Workplane:
        y = y if y is not None else x
        z = z if z is not None else x
        t = cq.Matrix([
            [x, 0, 0, 0],
            [0, y, 0, 0],
            [0, 0, z, 0],
            [0, 0, 0, 1]
            ])
        return workplane.newObject([
            o.transformGeometry(t) if isinstance(o, cq.Shape) else o
            for o in workplane.objects
    ])

    def assemblyThruster(self):
        try:
            self.thruster.add(self.pmu, name='pmu_box', loc=cq.Location(cq.Vector(0,0,0)),color=self.pmuRGB)
        except:
            print("PMU box was not added into the assembly.")
            
        try:
            self.thruster.add(self.logo_purple,name='logo_purp',loc=cq.Location(cq.Vector(0,0,self.pmuDictInit["thickness"]-self.logoDictInit["t_logo"])), color=self.purpleRGB)\
                .add(self.logo_green,name='logo_green',loc=cq.Location(cq.Vector(0,0,self.pmuDictInit["thickness"]-self.logoDictInit["t_logo"])), color=self.greenRGB)
        except:
            pass
        
        try:
            self.thruster.add(self.athena, name='athena', loc=cq.Location(cq.Vector(-self.factor_scale*6.211/2,-self.pc104[1]/2,(self.pmuDictInit["thickness"]-self.pmuDictInit["attach_height"])/2-self.factor_scale/2)),color=self.athenaRGB)
        except:
            pass
        
        try:
            self.thruster.add(self.ebox, name='PCB_stack_PC104_standard', loc=cq.Location(cq.Vector(0,0,-self.pc104[2])), color=self.eboxRGB)
            self.thruster.add(self.buskit, name='CubeSatKitBus', loc=cq.Location(cq.Vector(0,self.pcbAttachPoints[0][1]-self.connector["spacing"]*1.5,-self.pc104[2]-self.connector["thickness"])), color=self.busRGB)
        except:
            print("PPU box was not added into the assembly.")
            
        try:
            for k in range(0,self.pmuDictInit["n_emitter"]):
                self.thruster.add(self.emitter, name='emitter_case_'+str(k+1), loc=cq.Location(cq.Vector(self.emit_points[k][0],self.emit_points[k][1],self.pmuDictInit["thickness"]-self.emitterDictInit["depth"])))
        except:
            print("Emitters were not included into the assembly.")
        
        try:
            for k in range(0,self.pmuDictInit["n_emitter"]):
                self.thruster.add(self.grid, name='grid_'+str(k+1), loc=cq.Location(cq.Vector(self.emit_points[k][0],self.emit_points[k][1],self.pmuDictInit["thickness"]-self.emitterDictInit["t_grid"])))
        except:
            print("Grids were not included into the assembly.")
        
        return self.thruster
    
    def exportSTEP(self, path = None, name = None):
        self.extension = '.step'
        self.path = r'' if path is None else path
        self.name = r'AthenaCADv0.1' if name is None else name
        self.thruster.save(self.path + self.name + self.extension)

def generate_solid_from_assembly(assy, fuse=True, name_filter_re=None):
    result = []
    
    for name,val in assy.traverse():
        if name_filter_re and not re.match(name_filter_re, name):
            continue
        
        shape = val.obj.val()

        # get location
        loc = val.loc
        current = val
        while current.parent:
            loc = current.parent.loc*loc
            current = current.parent
        
        result.append(shape.located(loc))

    result = cq.Compound.makeCompound(result) 

    if fuse:
        result = result.fuse()

    return result



start_time = time.time()
var = {"height":85, "width":86, "thickness":30, "attach_height":5,"chamfer":12,"n_emitter":8}

test = CADCreator(var)
test.buildPMU()
test.buildEmitters()
test.buildLogo()
test.buildEbox()
test.buildAT()
thruster = test.assemblyThruster()
test.exportSTEP()
show_object(thruster)

assy_solid = generate_solid_from_assembly(thruster)
```

**Comment by davidvpspace** [comment]
> I have also try the solution from issue #629, but I get the following error:
> 
> `assy_solid = generate_solid_from_assembly(assy)`
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-7-bf842f15567a> in <module>
> ----> 1 assy_solid = generate_solid_from_assembly(assy)
> 
> <ipython-input-6-5f4c196566c5> in generate_solid_from_assembly(assy, fuse, name_filter_re)
>       6             continue
>       7 
> ----> 8         shape = val.obj.val()
>       9 
>      10         # get location
> 
> AttributeError: 'NoneType' object has no attribute 'val'
> ```

I was able to solve this. I was creating an empty assembly and then adding parts. The assembly was being created properly but when I tried to run the generate_solid_from_assembly function didnt work

```
assy = cq.Assembly()
assy.add(part1, name="part1")
assy.add(part2, name="part2")
```

**Comment by fedorkotov** [comment]
> I was able to solve this.

I'm glad that you have managed to solve this problem yourself.

> I was creating an empty assembly and then adding parts. The assembly was being created properly but when I tried to run the generate_solid_from_assembly function didnt work

Previously you posted and then deleted some huge piece of code depending on a DXF that you did not provide. Now after you have deleted that post your comment does not really explain what happened. Nobody except your knows what was inside `generate_solid_from_assembly ` function.
Please consider adding a short summary for the benefit of others who will come from google to this issue if you have time for this.

**Comment by davidvpspace** [comment]
> > I was able to solve this.
> 
> I'm glad that you have managed to solve this problem yourself.
> 
> > I was creating an empty assembly and then adding parts. The assembly was being created properly but when I tried to run the generate_solid_from_assembly function didnt work
> 
> Previously you posted and then deleted some huge piece of code depending on a DXF that you did not provide. Now after you have deleted that post your comment does not really explain what happened. Nobody except your knows what was inside `generate_solid_from_assembly ` function.
> Please consider adding a short summary for the benefit of others who will come from google to this issue if you have time for this.

Yes,  I realized that the whole code was too much for the simple question I was asking. The code inside generate_solid_from_assembly is the same as in #629 

```
def generate_solid_from_assembly(assy, fuse=True, name_filter_re=None):
    result = []
    
    for name,val in assy.traverse():
        if name_filter_re and not re.match(name_filter_re, name):
            continue
        
        shape = val.obj.val()

        # get location
        loc = val.loc
        current = val
        while current.parent:
            loc = current.parent.loc*loc
            current = current.parent
        
        result.append(shape.located(loc))

    result = cq.Compound.makeCompound(result) 

    if fuse:
        result = result.fuse()

    return result
```

I was giving the function an assembly that was initially created empty and then adding the parts:

```
assy = cq.Assembly()
assy.add(workplane1, name="part1")
assy.add(workplane2, name="part2")
assy_solid = generate_solid_from_assembly(assy)
```

This was an issue as the method val() was not recognized. On the other hand if I do:

```
assy = cq.Assembly(workplane1, name="part1")
assy.add(workplane2, name="part2")
assy_solid = generate_solid_from_assembly(assy)
```

works correctly.

To close this issue, what is the command line that I should write in the conda prompt to update cadquery to include the method toCompound(). This would replace the whole function. Thx!

**Comment by fedorkotov** [comment]
> To close this issue, what is the command line that I should write in the conda prompt to update cadquery to include the method toCompound(). This would replace the whole function. Thx!

As @Jojain said `toCompound()` was merged yesterday. So you should install the latest master from this repo.

Maybe this is not the correct way but I usually just delete conda environment where my copy of CadQuery is installed and reinstall everything as described in CadQuery [README](https://github.com/CadQuery/cadquery#getting-started) or with mamba (see #691). This avoids all possible version conflicts and ensures latest possible versions of all dependencies are installed.

There is also `conda update --all` (see https://stackoverflow.com/questions/38972052/anaconda-update-all-possible-packages for example).

**Comment by jmwright** [comment]
@davidvpspace You can try the following method, but what @fedorkotov has suggested about removing and re-creating the environment is the safest method. We have had multiple users end up with weird version conflicts when upgrading packages within environments.

```
conda remove cadquery
conda clean --all --force-pkgs-dirs
conda install --force-reinstall -c conda-forge -c cadquery=master
```

**Comment by adam-urbanczyk** [comment]
Please wait till azure on master is green (should happen soon).

**Comment by davidvpspace** [comment]
@jmwright I have done what you proposed of removing cadquery and reinstalling it, but now I get the following error. I have tried several time to delete all the files and installing it again, but the same happens:

```
>>> import cadquery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\david\anaconda3\envs\cadquery\lib\site-packages\cadquery\__init__.py", line 2, in <module>
    from .occ_impl.geom import Plane, BoundBox, Vector, Matrix, Location
  File "C:\Users\david\anaconda3\envs\cadquery\lib\site-packages\cadquery\occ_impl\geom.py", line 5, in <module>
    from OCP.gp import (
ImportError: DLL load failed while importing OCP: The specified module could not be found.
```

**Comment by jmwright** [comment]
CadQuery CI is green again, so you should be safe to try this now. Did you use the following steps to remove and recreate the environment?
```bash
conda deactivate # if you are in the cadquery environment
conda env remove -n cadquery # Should say "Removing all packages" and not give an error
conda create -n cadquery python=3.8 # I personally like to pin the version of Python
conda activate cadquery
conda install -c conda-forge -c cadquery cadquery=master
```
Then try `import cadquery`. If the steps above do not work, please post what OS you're running and what version of Anaconda/Miniconda/Mamba you are running.

**Comment by davidvpspace** [comment]
Now it works! (with the steps above) Thanks for your help!
