### ISSUE TITLE
DXF not round-trippable

### ISSUE THREAD

**Issue by leycec** [CadQuery/cadquery#904]
CadQuery's STEP import and export behaves *flawlessly,* probably thanks to the overpowering dark power of OCP + OCCT. That's great.

Sadly, CadQuery's DXF import and export behaves... *less flawlessly.* Specifically, I can't seem to round-trip [CadQuery's homebrew variant of the classic OCCT bottle](https://cadquery.readthedocs.io/en/latest/examples.html#the-classic-occ-bottle) through a DXF export-import cycle (i.e., by first exporting the CadQuery workplane for the bottle to DXF and then importing that DXF back into a CadQuery workplane). That's less great.

Minimal-length example or it didn't happen, so...

## To Reproduce

```python
import cadquery as cq
from os.path import join
from tempfile import TemporaryDirectory

(L, w, t) = (20.0, 6.0, 3.0)
s = cq.Workplane("XY")

# Draw half the profile of the bottle and extrude it
p = (s.center(-L/2.0, 0).vLine(w/2.0)
    .threePointArc((L/2.0, w/2.0 + t), (L, w/2.0)).vLine(-w/2.0)
    .mirrorX().extrude(30.0, True))

# Make the neck
p = p.faces(">Z").workplane(centerOption="CenterOfMass").circle(3.0).extrude(2.0, True)

# Make a shell
result = p.faces(">Z").shell(0.3)

with TemporaryDirectory() as tmp_dir:
    dxf_filename = join(tmp_dir, 'occt_bottle.dxf')
    cq.occ_impl.exporters.dxf.exportDXF(result, dxf_filename)
    cq.occ_impl.importers.importDXF(dxf_filename)
```

## Backtrace

```
Traceback (most recent call last):
  File "/home/leycec/tmp/cq_dxf_issue.py", line 24, in <module>
    cq.occ_impl.importers.importDXF(dxf_filename)
  File "/usr/lib/python3.9/site-packages/cadquery/occ_impl/importers.py", line 235, in importDXF
    wire_sets = sortWiresByBuildOrder(res)
  File "/usr/lib/python3.9/site-packages/cadquery/occ_impl/shapes.py", line 3240, in sortWiresByBuildOrder
    faces = Face.makeFromWires(wireList[0], wireList[1:])
  File "/usr/lib/python3.9/site-packages/cadquery/occ_impl/shapes.py", line 2164, in makeFromWires
    raise ValueError("Cannot build face(s): wires not planar")
ValueError: Cannot build face(s): wires not planar
```

On the off-hand chance this is a tolerance issue, I've played with the wire-building edge tolerance a bit by explicitly passing both smaller and larger `tol` parameters than `1e-6` to the above `importDXF()` call. Nothing helps, suggesting a more sinister issue at play.

## Environment

CadQuery: **CadQuery 2.2 release candidate (2021-08-04 snapshot)**

Python: **CPython 3.9.6**

OS: **Gentoo,** of course. [We (*...okay, it was me*) recently added support for a CadQuery 2.2 release candidate snapshotted on 2021-08-04 to our quasi-official `::science` overlay](https://github.com/gentoo/sci/pull/1108). Admittedly, this is a non-standard installation method.

If you can't replicate this issue on your end, @adam-urbanczyk, please immediately close this with my apologies. We'll then bump our CadQuery 2.2 ebuilds to newer and shinier snapshots of CadQuery and OCP.

Thanks for all the game-changing work, Adam & Crew. Lovin' it! :sparkling_heart:

**Comment by leycec** [comment]
> What are you trying to achieve with the code?

...that CadQuery can round-trip DXF.

No, seriously. Our data science app leverages CadQuery under the hood for CAD export and import. So, we assiduously unit test that CadQuery behaves as expected for all supported filetypes. The code above is verbatim from our test suite. `</shrug>`

> Only planar objects can be imported...

**Oh.** Fascinating. I don't recall tripping over that caveat in the documentation. Does this constraint apply only to the DXF importer or to the STEP importer as well?

In any case, we'll patch up our unit tests to reflect this. Thanks a bunch for the heads-up, Adam.

I'm no longer clear whether this is a bug, a feature request, or simply a misunderstanding on our part. If the latter, please close this (again) with our apologies.

**Comment by leycec** [comment]
**Right.** I didn't realize DXF was fundamentally planar in nature.

We'd expected DXF to behave more like a full-blown CAD interchange format (e.g., IGES, STEP). Thanks for the clarifications, Adam. Since this is clearly a string of bad assumptions on our end, I'll close this straightaway. :+1:
